### ISSUE TITLE
CR doesn't work with ES6+

### ISSUE THREAD

**Issue by sils1297** [escomplex/complexity-report#16]
CC @oreqizer

**Comment by sils1297** [comment]
ah https://github.com/escomplex/escomplex/issues/22

**Comment by typhonrt** [comment]
My next-gen fork [typhonjs-escomplex](https://www.npmjs.com/package/typhonjs-escomplex) will be complete sometime soon and rolls in all CR functionality including an expanded CLI and supports ES6+ and then some. Hang in there.
